# Generated by Django 3.0.5 on 2020-04-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200408_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog_img', verbose_name='博客图片'),
        ),
    ]
