# Generated by Django 3.0.5 on 2020-04-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='visiter',
        ),
    ]
